### ISSUE TITLE
Deprecated Alias warning in logs

### ISSUE THREAD

**Issue by ben-maher** [kbirger/ha-smarter-integration#81]
## Version of the custom_component

0.3.1

## Configuration

```yaml
Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 2:51:46 PM (1 occurrences)
Last logged: 2:51:46 PM

Config was used from smarter, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'smarter' custom integration
```

## Describe the bug

Not a bug, a heads up - I've just started using this and noticed a log in Home Assistant warning of a deprecated alias.

## Debug log

```text

Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 2:51:46 PM (1 occurrences)
Last logged: 2:51:46 PM

Config was used from smarter, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'smarter' custom integration

```
